/*:
 # Simple harmonic Motion
 In some cases when observe in the motion of an object, it will involve a single action, like a rock falling from a cliff down to the ground. This motion is gonna happen just for one time, ending when the rock reaches the ground. But some motions are periodic, or repeated, like the motion of the pendulum on a old clock, or the vibration of a spring.
 
 ![Harmonic motion graphic](harmonic_motion.png)
 
 We call this kind of motion by Simple Harmonic Motion because the graphic generated by the position against time generates a sinusoidal wave. The mathematicians loves sinusoidal wave, because already exists equations about it.
 
 ## Movement
 As you can see beside we have a spring that is attached to some surface, and on the other end of the spring there is a block with mass.
 
 * callout(Tip):
 Tap the "Play" button to see the blocks being pushed or stretched.
 
 If you pull this block so as to expand the spring and then you release, it will vibrate back and forth between more compressed and less compressed states. If we assume that the surface of motion is completely frictionless and there's no air resistance then the spring would motion forever!
 
 - Note:
 In this case, the surface and the block have some friction, that's why the spring lost force in each moving.
 
 # Equilibrium point
 As you notice the spring always try to get back to the point when it's in its normal state. When the block compresses the spring it will push out, and when the block stretches the spring it will pull in. So that's the rule of thumb: the spring always try to get back to the _equilibrium position_.
 
 This opposite force is always negative, like says Hooke's Law. That's our next subject.
 
 [Next Page](@next)
 
 */
